#!/usr/bin/env bash
# Script configures Nginx to listen on port 80

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Update Nginx configuration to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

# Ensure Nginx is running and listening on port 80
netstat -tuln | grep 80
